name: Deploy Strapi to ECS Fargate

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Terraform Deploy to AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Debug
        run: |
          terraform fmt
          terraform fmt -check
        working-directory: terraform3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform3

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform3

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform3
